# Generated by Django 2.1.2 on 2018-10-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='public_data',
            new_name='public_date',
        ),
    ]
